# encoding catagorical data
catagorical data:  1.Nominal: no hirarchy/ valueable difference in data.

                2.Ordinal: eg. good,bad; high,low,mid;

# techniques:
1. Ordinal encoding:
2. label encoding

In [2]:
import pandas as pd

In [5]:
df=pd.read_csv("customer.csv")

In [40]:
df

age  gender   review education purchased
0    30  Female  Average    School        No
1    68  Female     Poor        UG        No
2    70  Female     Good        PG        No
3    72  Female     Good        PG        No
4    16  Female  Average        UG        No
5    31  Female  Average    School       Yes
6    18    Male     Good    School        No
7    60  Female     Poor    School       Yes
8    65  Female  Average        UG        No
9    74    Male     Good        UG       Yes
10   98  Female     Good        UG       Yes
11   74    Male     Good        UG       Yes
12   51    Male     Poor    School        No
13   57  Female  Average    School        No
14   15    Male     Poor        PG       Yes
15   75    Male     Poor        UG        No
16   59    Male     Poor        UG       Yes
17   22  Female     Poor        UG       Yes
18   19    Male     Good    School        No
19   97    Male     Poor        PG       Yes
20   57  Female  Average    School       Yes
21   32    Male  Average        PG        No
22   18  Female     Poor        PG       Yes
23   96  Female     Good    School        No
24   16  Female  Average        PG       Yes
25   57  Female     Good    School        No
26   53  Female     Poor        PG        No
27   69  Female     Poor        PG        No
28   48    Male     Poor    School        No
29   83  Female  Average        UG       Yes
30   73    Male  Average        UG        No
31   22  Female     Poor    School       Yes
32   92    Male  Average        UG       Yes
33   89  Female     Good        PG       Yes
34   86    Male  Average    School        No
35   74    Male     Poor    School       Yes
36   34  Female     Good        UG       Yes
37   94    Male  Average        PG       Yes
38   45  Female     Good    School        No
39   76    Male     Poor        PG        No
40   39    Male     Good    School        No
41   23    Male     Good        PG       Yes
42   30  Female     Good        PG       Yes
43   27    Male     Poor        PG        No
44   77  Female  Average        UG        No
45   61    Male     Poor        PG       Yes
46   64  Female     Poor        PG        No
47   38  Female     Good        PG       Yes
48   39  Female     Good        UG       Yes
49   25  Female     Good        UG        No

In [6]:
df1=df.iloc[:,2:]

In [7]:
df1.head()

review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [22]:
from sklearn.model_selection import train_test_split

In [18]:
from sklearn.preprocessing import OrdinalEncoder

In [36]:
x_train, x_test, y_train, y_test = train_test_split(df1.iloc[:,0:2],df.iloc[:,-1],test_size=0.2,random_state=0)
x_train.head()

review education
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School

In [17]:
oe = OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [18]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [19]:
x_train = oe.transform(x_train)

In [23]:
x_train.head()

review education
33     Good        PG
35     Poor    School
26     Poor        PG
34  Average    School
18     Good    School

In [20]:
from sklearn.preprocessing import LabelEncoder

In [25]:
le = LabelEncoder()

In [26]:
le.fit(y_train)

LabelEncoder()

In [28]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [37]:
y_train = le.transform(y_train)

In [38]:
y_test = le.transform(y_test)

In [39]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0])

One hot encoding on gender:(using pandas)

In [6]:
gender=pd.get_dummies(df['gender'],drop_first=True)
gender

Male
0   False
1   False
2   False
3   False
4   False
5   False
6    True
7   False
8   False
9    True
10  False
11   True
12   True
13  False
14   True
15   True
16   True
17  False
18   True
19   True
20  False
21   True
22  False
23  False
24  False
25  False
26  False
27  False
28   True
29  False
30   True
31  False
32   True
33  False
34   True
35   True
36  False
37   True
38  False
39   True
40   True
41   True
42  False
43   True
44  False
45   True
46  False
47  False
48  False
49  False

In [10]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

In [12]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype = np.int32)

In [14]:
gender_new= ohe.fit_transform(df['gender'].to_frame())
gender_new

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0]])

At the end, we concatenate all the rows

# Mentos Jindagi (column Transformer):

In [7]:
from sklearn.compose import ColumnTransformer

In [66]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', OneHotEncoder(drop='first', sparse_output=False),['gender']),
    ('tnf2', OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']]),['review', 'education'])
],remainder='passthrough')


#('tnf3', LabelEncoder(), ['purchased'])could have been used but since its output column

In [67]:
x_train, x_test, y_train, y_test = train_test_split(df.drop(columns=['purchased']),df['purchased'],test_size=0.2)
x_train

age  gender   review education
9    74    Male     Good        UG
33   89  Female     Good        PG
47   38  Female     Good        PG
6    18    Male     Good    School
5    31  Female  Average    School
1    68  Female     Poor        UG
31   22  Female     Poor    School
7    60  Female     Poor    School
19   97    Male     Poor        PG
29   83  Female  Average        UG
42   30  Female     Good        PG
35   74    Male     Poor    School
46   64  Female     Poor        PG
16   59    Male     Poor        UG
34   86    Male  Average    School
28   48    Male     Poor    School
21   32    Male  Average        PG
40   39    Male     Good    School
11   74    Male     Good        UG
0    30  Female  Average    School
3    72  Female     Good        PG
2    70  Female     Good        PG
43   27    Male     Poor        PG
10   98  Female     Good        UG
17   22  Female     Poor        UG
27   69  Female     Poor        PG
12   51    Male     Poor    School
26   53  Female     Poor        PG
23   96  Female     Good    School
30   73    Male  Average        UG
41   23    Male     Good        PG
13   57  Female  Average    School
15   75    Male     Poor        UG
14   15    Male     Poor        PG
20   57  Female  Average    School
44   77  Female  Average        UG
45   61    Male     Poor        PG
38   45  Female     Good    School
4    16  Female  Average        UG
8    65  Female  Average        UG

In [68]:
transformer.fit_transform(x_train)

array([[ 1.,  2.,  1., 74.],
       [ 0.,  2.,  2., 89.],
       [ 0.,  2.,  2., 38.],
       [ 1.,  2.,  0., 18.],
       [ 0.,  1.,  0., 31.],
       [ 0.,  0.,  1., 68.],
       [ 0.,  0.,  0., 22.],
       [ 0.,  0.,  0., 60.],
       [ 1.,  0.,  2., 97.],
       [ 0.,  1.,  1., 83.],
       [ 0.,  2.,  2., 30.],
       [ 1.,  0.,  0., 74.],
       [ 0.,  0.,  2., 64.],
       [ 1.,  0.,  1., 59.],
       [ 1.,  1.,  0., 86.],
       [ 1.,  0.,  0., 48.],
       [ 1.,  1.,  2., 32.],
       [ 1.,  2.,  0., 39.],
       [ 1.,  2.,  1., 74.],
       [ 0.,  1.,  0., 30.],
       [ 0.,  2.,  2., 72.],
       [ 0.,  2.,  2., 70.],
       [ 1.,  0.,  2., 27.],
       [ 0.,  2.,  1., 98.],
       [ 0.,  0.,  1., 22.],
       [ 0.,  0.,  2., 69.],
       [ 1.,  0.,  0., 51.],
       [ 0.,  0.,  2., 53.],
       [ 0.,  2.,  0., 96.],
       [ 1.,  1.,  1., 73.],
       [ 1.,  2.,  2., 23.],
       [ 0.,  1.,  0., 57.],
       [ 1.,  0.,  1., 75.],
       [ 1.,  0.,  2., 15.],
       [ 0.,  